name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ruixinlou
        password: HZhzlrx0612
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ruixinlou/project2:latest
    # - name: Test with pytest
    #   run: |
    #     make test
    - name: Format code
      run: |
        make format
